//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace SmartHaiShu.CityScreenServices.SocialInsureService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SocialInsureServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SocialInsureService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSocialInsureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SocialInsureService() {
            this.Url = global::SmartHaiShu.CityScreenServices.Properties.Settings.Default.SmartHaiShu_CityScreenServices_SocialInsureService_SocialInsureService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSocialInsureCompletedEventHandler GetSocialInsureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSocialInsure", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MonthInsure[] GetSocialInsure(string IDCard, string Password, out AccountInfo account, out MedicalInsure medIn) {
            object[] results = this.Invoke("GetSocialInsure", new object[] {
                        IDCard,
                        Password});
            account = ((AccountInfo)(results[1]));
            medIn = ((MedicalInsure)(results[2]));
            return ((MonthInsure[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSocialInsureAsync(string IDCard, string Password) {
            this.GetSocialInsureAsync(IDCard, Password, null);
        }
        
        /// <remarks/>
        public void GetSocialInsureAsync(string IDCard, string Password, object userState) {
            if ((this.GetSocialInsureOperationCompleted == null)) {
                this.GetSocialInsureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSocialInsureOperationCompleted);
            }
            this.InvokeAsync("GetSocialInsure", new object[] {
                        IDCard,
                        Password}, this.GetSocialInsureOperationCompleted, userState);
        }
        
        private void OnGetSocialInsureOperationCompleted(object arg) {
            if ((this.GetSocialInsureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSocialInsureCompleted(this, new GetSocialInsureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MonthInsure {
        
        private string shenbaoNYField;
        
        private string daozhangNYField;
        
        private string jiaofeiJSField;
        
        private string danweiJFField;
        
        private string gerenBFField;
        
        private string jiaofeiYSField;
        
        /// <remarks/>
        public string ShenbaoNY {
            get {
                return this.shenbaoNYField;
            }
            set {
                this.shenbaoNYField = value;
            }
        }
        
        /// <remarks/>
        public string DaozhangNY {
            get {
                return this.daozhangNYField;
            }
            set {
                this.daozhangNYField = value;
            }
        }
        
        /// <remarks/>
        public string JiaofeiJS {
            get {
                return this.jiaofeiJSField;
            }
            set {
                this.jiaofeiJSField = value;
            }
        }
        
        /// <remarks/>
        public string DanweiJF {
            get {
                return this.danweiJFField;
            }
            set {
                this.danweiJFField = value;
            }
        }
        
        /// <remarks/>
        public string GerenBF {
            get {
                return this.gerenBFField;
            }
            set {
                this.gerenBFField = value;
            }
        }
        
        /// <remarks/>
        public string JiaofeiYS {
            get {
                return this.jiaofeiYSField;
            }
            set {
                this.jiaofeiYSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MedicalInsure {
        
        private string insureStField;
        
        private string clientNameField;
        
        private string iDcardField;
        
        private string yibaohaoField;
        
        private string kahaoField;
        
        private string daiyuLXField;
        
        private string dangqianDYField;
        
        private string dangnianYEField;
        
        private string linianYEField;
        
        private string menzhenFeeField;
        
        private string zhuyuanFeeField;
        
        private string zhuyuanLJField;
        
        private string jiezhiDateField;
        
        /// <remarks/>
        public string InsureSt {
            get {
                return this.insureStField;
            }
            set {
                this.insureStField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string IDcard {
            get {
                return this.iDcardField;
            }
            set {
                this.iDcardField = value;
            }
        }
        
        /// <remarks/>
        public string Yibaohao {
            get {
                return this.yibaohaoField;
            }
            set {
                this.yibaohaoField = value;
            }
        }
        
        /// <remarks/>
        public string Kahao {
            get {
                return this.kahaoField;
            }
            set {
                this.kahaoField = value;
            }
        }
        
        /// <remarks/>
        public string DaiyuLX {
            get {
                return this.daiyuLXField;
            }
            set {
                this.daiyuLXField = value;
            }
        }
        
        /// <remarks/>
        public string DangqianDY {
            get {
                return this.dangqianDYField;
            }
            set {
                this.dangqianDYField = value;
            }
        }
        
        /// <remarks/>
        public string DangnianYE {
            get {
                return this.dangnianYEField;
            }
            set {
                this.dangnianYEField = value;
            }
        }
        
        /// <remarks/>
        public string LinianYE {
            get {
                return this.linianYEField;
            }
            set {
                this.linianYEField = value;
            }
        }
        
        /// <remarks/>
        public string MenzhenFee {
            get {
                return this.menzhenFeeField;
            }
            set {
                this.menzhenFeeField = value;
            }
        }
        
        /// <remarks/>
        public string ZhuyuanFee {
            get {
                return this.zhuyuanFeeField;
            }
            set {
                this.zhuyuanFeeField = value;
            }
        }
        
        /// <remarks/>
        public string ZhuyuanLJ {
            get {
                return this.zhuyuanLJField;
            }
            set {
                this.zhuyuanLJField = value;
            }
        }
        
        /// <remarks/>
        public string JiezhiDate {
            get {
                return this.jiezhiDateField;
            }
            set {
                this.jiezhiDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInfo {
        
        private string sINOField;
        
        private string insureTypeField;
        
        private string clientNameField;
        
        /// <remarks/>
        public string SINO {
            get {
                return this.sINOField;
            }
            set {
                this.sINOField = value;
            }
        }
        
        /// <remarks/>
        public string InsureType {
            get {
                return this.insureTypeField;
            }
            set {
                this.insureTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetSocialInsureCompletedEventHandler(object sender, GetSocialInsureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSocialInsureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSocialInsureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MonthInsure[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MonthInsure[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public AccountInfo account {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountInfo)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public MedicalInsure medIn {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MedicalInsure)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591