//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_t_ufp_4_2_6
    {
        // Primitive properties
    
        public string UUID { get; set; }
        public string IMPORT_PORT { get; set; }
        public string ADDRESS { get; set; }
        public string PAUSE_ADD { get; set; }
        public string FLIGHT { get; set; }
        public string TYPE1 { get; set; }
        public string LEAVE1 { get; set; }
        public string PAUSE { get; set; }
        public string ARRIVE { get; set; }
        public string LIMIT1 { get; set; }
        public string TIME_SLOT { get; set; }
        public string RELEASE_TIME { get; set; }
        public string DATA_SRC { get; set; }
        public string CHECK_TIME { get; set; }
    
    }
}
