//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class community
    {
        public community()
        {
            this.member = new HashSet<member>();
        }
    
        // Primitive properties
    
        public int community_id { get; set; }
        public string name { get; set; }
        public int parent_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<member> member { get; set; }
    
    }
}
