//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dzk_bzdzk
    {
        // Primitive properties
    
        public string TD_Y { get; set; }
        public string TD_X { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<System.DateTime> DMBQYDate { get; set; }
        public Nullable<System.DateTime> ZXDate { get; set; }
        public Nullable<int> ZXBZ { get; set; }
        public string WZJZ { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Floor { get; set; }
        public string XQLY { get; set; }
        public string DLX { get; set; }
        public string HM { get; set; }
        public string ZM { get; set; }
        public string NM { get; set; }
        public string LM { get; set; }
        public string Address { get; set; }
        public string SQ { get; set; }
        public string JD { get; set; }
        public int QX { get; set; }
        public int Build_ID { get; set; }
        public int ID { get; set; }
    
    }
}
