//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class global_type_config
    {
        // Primitive properties
    
        public int type_id { get; set; }
        public string type_name { get; set; }
        public int category_id { get; set; }
        public bool valid { get; set; }
    
    }
}
