//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class interact_post
    {
        // Primitive properties
    
        public long post_id { get; set; }
        public string title { get; set; }
        public Nullable<long> member_id { get; set; }
        public string member_name { get; set; }
        public string content { get; set; }
        public string keyword { get; set; }
        public string contact_info { get; set; }
        public Nullable<int> data_span { get; set; }
        public System.DateTime release_time { get; set; }
        public Nullable<int> state { get; set; }
    
        // Navigation properties
    
        public virtual member member { get; set; }
    
    }
}
