//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Data.Entity;
    
    public partial class HsSmartEntities : DbContext
    {
        public HsSmartEntities()
            : base("name=HsSmartEntities")
        {
        }
    
    
        public DbSet<b_t_ufp_0003_cs> Db_b_t_ufp_0003_cs { get; set; }
    
        public DbSet<b_t_ufp_0003_ydml> Db_b_t_ufp_0003_ydml { get; set; }
    
        public DbSet<b_t_ufp_0003_yh> Db_b_t_ufp_0003_yh { get; set; }
    
        public DbSet<b_t_ufp_1_1> Db_b_t_ufp_1_1 { get; set; }
    
        public DbSet<b_t_ufp_1_2> Db_b_t_ufp_1_2 { get; set; }
    
        public DbSet<b_t_ufp_3_1_5> Db_b_t_ufp_3_1_5 { get; set; }
    
        public DbSet<b_t_ufp_3_1_6> Db_b_t_ufp_3_1_6 { get; set; }
    
        public DbSet<b_t_ufp_3_2_1> Db_b_t_ufp_3_2_1 { get; set; }
    
        public DbSet<b_t_ufp_3_2_2> Db_b_t_ufp_3_2_2 { get; set; }
    
        public DbSet<b_t_ufp_3_2_3> Db_b_t_ufp_3_2_3 { get; set; }
    
        public DbSet<b_t_ufp_3_2_4> Db_b_t_ufp_3_2_4 { get; set; }
    
        public DbSet<b_t_ufp_3_2_5> Db_b_t_ufp_3_2_5 { get; set; }
    
        public DbSet<b_t_ufp_4_1_2> Db_b_t_ufp_4_1_2 { get; set; }
    
        public DbSet<b_t_ufp_4_2_1> Db_b_t_ufp_4_2_1 { get; set; }
    
        public DbSet<b_t_ufp_4_2_6> Db_b_t_ufp_4_2_6 { get; set; }
    
        public DbSet<b_t_ufp_4_2_7> Db_b_t_ufp_4_2_7 { get; set; }
    
        public DbSet<b_t_ufp_4_3_1> Db_b_t_ufp_4_3_1 { get; set; }
    
        public DbSet<b_t_ufp_4_3_2> Db_b_t_ufp_4_3_2 { get; set; }
    
        public DbSet<b_t_ufp_4_3_3> Db_b_t_ufp_4_3_3 { get; set; }
    
        public DbSet<b_t_ufp_4_3_5> Db_b_t_ufp_4_3_5 { get; set; }
    
        public DbSet<b_t_ufp_4_5_1> Db_b_t_ufp_4_5_1 { get; set; }
    
        public DbSet<b_t_ufp_4_5_2> Db_b_t_ufp_4_5_2 { get; set; }
    
        public DbSet<b_t_ufp_6_1_1> Db_b_t_ufp_6_1_1 { get; set; }
    
        public DbSet<b_t_ufp_6_1_2> Db_b_t_ufp_6_1_2 { get; set; }
    
        public DbSet<b_t_ufp_8_4> Db_b_t_ufp_8_4 { get; set; }
    
        public DbSet<dzk_bzdzk> Db_dzk_bzdzk { get; set; }
    
        public DbSet<dzk_bzxxdzk> Db_dzk_bzxxdzk { get; set; }
    
        public DbSet<dzk_jzwdzk> Db_dzk_jzwdzk { get; set; }
    }
}
