//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_verify
    {
        // Primitive properties
    
        public long id { get; set; }
        public int type { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string session_key { get; set; }
        public string verify_code { get; set; }
    
    }
}
