//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaisuModel
{
    using System;
    using System.Data.Entity;
    
    public partial class SmartHsContext : DbContext
    {
        public SmartHsContext()
            : base("name=SmartHsContext")
        {
        }
    
        public DbSet<community> Db_community { get; set; }
        public DbSet<member> Db_member { get; set; }
        public DbSet<v_community> Db_v_community { get; set; }
        public DbSet<v_member> Db_v_member { get; set; }
        public DbSet<session_verify> Db_session_verify { get; set; }
    }
}
