//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaiShu_WebApp.HSOpenDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HSOpenDataService.IOpenDataService")]
    public interface IOpenDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityIntroduction", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityIntroductionResponse")]
        string GetCommunityIntroduction(string community);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityName", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNameResponse")]
        string GetCommunityName(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityNotice", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNoticeResponse")]
        string GetCommunityNotice(string noticeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityNoticeTitles", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNoticeTitlesResponse")]
        string GetCommunityNoticeTitles(string community);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityNoticeCount", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNoticeCountResponse")]
        string GetCommunityNoticeCount(string community);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityNoticeTitleByPage", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNoticeTitleByPageResponse")]
        string GetCommunityNoticeTitleByPage(string community, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityNoticeByPage", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNoticeByPageResponse")]
        string GetCommunityNoticeByPage(string community, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityFCCount", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityFCCountResponse")]
        string GetCommunityFCCount(string community);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityFCTitles", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityFCTitlesResponse")]
        string GetCommunityFCTitles(string community, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityFCByPage", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityFCByPageResponse")]
        string GetCommunityFCByPage(string community, int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityFC", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityFCResponse")]
        string GetCommunityFC(string fcId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetWaterNoticeCount", ReplyAction="http://tempuri.org/IOpenDataService/GetWaterNoticeCountResponse")]
        string GetWaterNoticeCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetWaterNotice", ReplyAction="http://tempuri.org/IOpenDataService/GetWaterNoticeResponse")]
        string GetWaterNotice(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetElectricNoticeCount", ReplyAction="http://tempuri.org/IOpenDataService/GetElectricNoticeCountResponse")]
        string GetElectricNoticeCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetElectricNotice", ReplyAction="http://tempuri.org/IOpenDataService/GetElectricNoticeResponse")]
        string GetElectricNotice(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetBusRoute", ReplyAction="http://tempuri.org/IOpenDataService/GetBusRouteResponse")]
        string GetBusRoute(string routeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetBusRouteCount", ReplyAction="http://tempuri.org/IOpenDataService/GetBusRouteCountResponse")]
        string GetBusRouteCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetBusRouteList", ReplyAction="http://tempuri.org/IOpenDataService/GetBusRouteListResponse")]
        string GetBusRouteList(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCar4SLocationCount", ReplyAction="http://tempuri.org/IOpenDataService/GetCar4SLocationCountResponse")]
        string GetCar4SLocationCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCar4SLocation", ReplyAction="http://tempuri.org/IOpenDataService/GetCar4SLocationResponse")]
        string GetCar4SLocation(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCarRepairLocationCount", ReplyAction="http://tempuri.org/IOpenDataService/GetCarRepairLocationCountResponse")]
        string GetCarRepairLocationCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCarRepairLocation", ReplyAction="http://tempuri.org/IOpenDataService/GetCarRepairLocationResponse")]
        string GetCarRepairLocation(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCarAnnualCheckCount", ReplyAction="http://tempuri.org/IOpenDataService/GetCarAnnualCheckCountResponse")]
        string GetCarAnnualCheckCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCarAnnualCheck", ReplyAction="http://tempuri.org/IOpenDataService/GetCarAnnualCheckResponse")]
        string GetCarAnnualCheck(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCarSchool", ReplyAction="http://tempuri.org/IOpenDataService/GetCarSchoolResponse")]
        string GetCarSchool(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCarSchoolCount", ReplyAction="http://tempuri.org/IOpenDataService/GetCarSchoolCountResponse")]
        string GetCarSchoolCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetStarHotelCount", ReplyAction="http://tempuri.org/IOpenDataService/GetStarHotelCountResponse")]
        string GetStarHotelCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetStarHotels", ReplyAction="http://tempuri.org/IOpenDataService/GetStarHotelsResponse")]
        string GetStarHotels(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetFlowerHotelCount", ReplyAction="http://tempuri.org/IOpenDataService/GetFlowerHotelCountResponse")]
        string GetFlowerHotelCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetFlowerHotels", ReplyAction="http://tempuri.org/IOpenDataService/GetFlowerHotelsResponse")]
        string GetFlowerHotels(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetChildSchoolCount", ReplyAction="http://tempuri.org/IOpenDataService/GetChildSchoolCountResponse")]
        string GetChildSchoolCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetChildSchool", ReplyAction="http://tempuri.org/IOpenDataService/GetChildSchoolResponse")]
        string GetChildSchool(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetPrimarySchoolCount", ReplyAction="http://tempuri.org/IOpenDataService/GetPrimarySchoolCountResponse")]
        string GetPrimarySchoolCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetPrimarySchool", ReplyAction="http://tempuri.org/IOpenDataService/GetPrimarySchoolResponse")]
        string GetPrimarySchool(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetRetirementHomeCount", ReplyAction="http://tempuri.org/IOpenDataService/GetRetirementHomeCountResponse")]
        string GetRetirementHomeCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetRetirementHome", ReplyAction="http://tempuri.org/IOpenDataService/GetRetirementHomeResponse")]
        string GetRetirementHome(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetMarketCount", ReplyAction="http://tempuri.org/IOpenDataService/GetMarketCountResponse")]
        string GetMarketCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetMarket", ReplyAction="http://tempuri.org/IOpenDataService/GetMarketResponse")]
        string GetMarket(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetDrugStoreCount", ReplyAction="http://tempuri.org/IOpenDataService/GetDrugStoreCountResponse")]
        string GetDrugStoreCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetDrugStore", ReplyAction="http://tempuri.org/IOpenDataService/GetDrugStoreResponse")]
        string GetDrugStore(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetBankLocationCount", ReplyAction="http://tempuri.org/IOpenDataService/GetBankLocationCountResponse")]
        string GetBankLocationCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetBankLocation", ReplyAction="http://tempuri.org/IOpenDataService/GetBankLocationResponse")]
        string GetBankLocation(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetBikeLocationCount", ReplyAction="http://tempuri.org/IOpenDataService/GetBikeLocationCountResponse")]
        string GetBikeLocationCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetBikeLocation", ReplyAction="http://tempuri.org/IOpenDataService/GetBikeLocationResponse")]
        string GetBikeLocation(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetFlightCount", ReplyAction="http://tempuri.org/IOpenDataService/GetFlightCountResponse")]
        string GetFlightCount(bool import);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetFlights", ReplyAction="http://tempuri.org/IOpenDataService/GetFlightsResponse")]
        string GetFlights(bool import, int pageNo, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOpenDataServiceChannel : SmartHaiShu_WebApp.HSOpenDataService.IOpenDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenDataServiceClient : System.ServiceModel.ClientBase<SmartHaiShu_WebApp.HSOpenDataService.IOpenDataService>, SmartHaiShu_WebApp.HSOpenDataService.IOpenDataService {
        
        public OpenDataServiceClient() {
        }
        
        public OpenDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpenDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCommunityIntroduction(string community) {
            return base.Channel.GetCommunityIntroduction(community);
        }
        
        public string GetCommunityName(string address) {
            return base.Channel.GetCommunityName(address);
        }
        
        public string GetCommunityNotice(string noticeId) {
            return base.Channel.GetCommunityNotice(noticeId);
        }
        
        public string GetCommunityNoticeTitles(string community) {
            return base.Channel.GetCommunityNoticeTitles(community);
        }
        
        public string GetCommunityNoticeCount(string community) {
            return base.Channel.GetCommunityNoticeCount(community);
        }
        
        public string GetCommunityNoticeTitleByPage(string community, int pageNo, int pageSize) {
            return base.Channel.GetCommunityNoticeTitleByPage(community, pageNo, pageSize);
        }
        
        public string GetCommunityNoticeByPage(string community, int pageNo, int pageSize) {
            return base.Channel.GetCommunityNoticeByPage(community, pageNo, pageSize);
        }
        
        public string GetCommunityFCCount(string community) {
            return base.Channel.GetCommunityFCCount(community);
        }
        
        public string GetCommunityFCTitles(string community, int pageNo, int pageSize) {
            return base.Channel.GetCommunityFCTitles(community, pageNo, pageSize);
        }
        
        public string GetCommunityFCByPage(string community, int pageNo, int pageSize) {
            return base.Channel.GetCommunityFCByPage(community, pageNo, pageSize);
        }
        
        public string GetCommunityFC(string fcId) {
            return base.Channel.GetCommunityFC(fcId);
        }
        
        public string GetWaterNoticeCount() {
            return base.Channel.GetWaterNoticeCount();
        }
        
        public string GetWaterNotice(int pageNo, int pageSize) {
            return base.Channel.GetWaterNotice(pageNo, pageSize);
        }
        
        public string GetElectricNoticeCount() {
            return base.Channel.GetElectricNoticeCount();
        }
        
        public string GetElectricNotice(int pageNo, int pageSize) {
            return base.Channel.GetElectricNotice(pageNo, pageSize);
        }
        
        public string GetBusRoute(string routeName) {
            return base.Channel.GetBusRoute(routeName);
        }
        
        public string GetBusRouteCount() {
            return base.Channel.GetBusRouteCount();
        }
        
        public string GetBusRouteList(int pageNo, int pageSize) {
            return base.Channel.GetBusRouteList(pageNo, pageSize);
        }
        
        public string GetCar4SLocationCount() {
            return base.Channel.GetCar4SLocationCount();
        }
        
        public string GetCar4SLocation(int pageNo, int pageSize) {
            return base.Channel.GetCar4SLocation(pageNo, pageSize);
        }
        
        public string GetCarRepairLocationCount() {
            return base.Channel.GetCarRepairLocationCount();
        }
        
        public string GetCarRepairLocation(int pageNo, int pageSize) {
            return base.Channel.GetCarRepairLocation(pageNo, pageSize);
        }
        
        public string GetCarAnnualCheckCount() {
            return base.Channel.GetCarAnnualCheckCount();
        }
        
        public string GetCarAnnualCheck(int pageNo, int pageSize) {
            return base.Channel.GetCarAnnualCheck(pageNo, pageSize);
        }
        
        public string GetCarSchool(int pageNo, int pageSize) {
            return base.Channel.GetCarSchool(pageNo, pageSize);
        }
        
        public string GetCarSchoolCount() {
            return base.Channel.GetCarSchoolCount();
        }
        
        public string GetStarHotelCount() {
            return base.Channel.GetStarHotelCount();
        }
        
        public string GetStarHotels(int pageNo, int pageSize) {
            return base.Channel.GetStarHotels(pageNo, pageSize);
        }
        
        public string GetFlowerHotelCount() {
            return base.Channel.GetFlowerHotelCount();
        }
        
        public string GetFlowerHotels(int pageNo, int pageSize) {
            return base.Channel.GetFlowerHotels(pageNo, pageSize);
        }
        
        public string GetChildSchoolCount() {
            return base.Channel.GetChildSchoolCount();
        }
        
        public string GetChildSchool(int pageNo, int pageSize) {
            return base.Channel.GetChildSchool(pageNo, pageSize);
        }
        
        public string GetPrimarySchoolCount() {
            return base.Channel.GetPrimarySchoolCount();
        }
        
        public string GetPrimarySchool(int pageNo, int pageSize) {
            return base.Channel.GetPrimarySchool(pageNo, pageSize);
        }
        
        public string GetRetirementHomeCount() {
            return base.Channel.GetRetirementHomeCount();
        }
        
        public string GetRetirementHome(int pageNo, int pageSize) {
            return base.Channel.GetRetirementHome(pageNo, pageSize);
        }
        
        public string GetMarketCount() {
            return base.Channel.GetMarketCount();
        }
        
        public string GetMarket(int pageNo, int pageSize) {
            return base.Channel.GetMarket(pageNo, pageSize);
        }
        
        public string GetDrugStoreCount() {
            return base.Channel.GetDrugStoreCount();
        }
        
        public string GetDrugStore(int pageNo, int pageSize) {
            return base.Channel.GetDrugStore(pageNo, pageSize);
        }
        
        public string GetBankLocationCount() {
            return base.Channel.GetBankLocationCount();
        }
        
        public string GetBankLocation(int pageNo, int pageSize) {
            return base.Channel.GetBankLocation(pageNo, pageSize);
        }
        
        public string GetBikeLocationCount() {
            return base.Channel.GetBikeLocationCount();
        }
        
        public string GetBikeLocation(int pageNo, int pageSize) {
            return base.Channel.GetBikeLocation(pageNo, pageSize);
        }
        
        public string GetFlightCount(bool import) {
            return base.Channel.GetFlightCount(import);
        }
        
        public string GetFlights(bool import, int pageNo, int pageSize) {
            return base.Channel.GetFlights(import, pageNo, pageSize);
        }
    }
}
