//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaiShu.WcfService.PriceMexService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodMonitor", Namespace="http://schemas.datacontract.org/2004/07/CityInfoScreenWcf")]
    [System.SerializableAttribute()]
    public partial class FoodMonitor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetricsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadtimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AutoID {
            get {
                return this.AutoIDField;
            }
            set {
                if ((this.AutoIDField.Equals(value) != true)) {
                    this.AutoIDField = value;
                    this.RaisePropertyChanged("AutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID {
            get {
                return this.FoodIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodIDField, value) != true)) {
                    this.FoodIDField = value;
                    this.RaisePropertyChanged("FoodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metrics {
            get {
                return this.MetricsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetricsField, value) != true)) {
                    this.MetricsField = value;
                    this.RaisePropertyChanged("Metrics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIDField, value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName {
            get {
                return this.SiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteNameField, value) != true)) {
                    this.SiteNameField = value;
                    this.RaisePropertyChanged("SiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spec {
            get {
                return this.SpecField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecField, value) != true)) {
                    this.SpecField = value;
                    this.RaisePropertyChanged("Spec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Uploadtime {
            get {
                return this.UploadtimeField;
            }
            set {
                if ((this.UploadtimeField.Equals(value) != true)) {
                    this.UploadtimeField = value;
                    this.RaisePropertyChanged("Uploadtime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PriceMexService.IPrice")]
    public interface IPrice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/ExsitesFoodMonitor", ReplyAction="http://tempuri.org/IPrice/ExsitesFoodMonitorResponse")]
        bool ExsitesFoodMonitor(long AutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetFoodMonitorById", ReplyAction="http://tempuri.org/IPrice/GetFoodMonitorByIdResponse")]
        SmartHaiShu.WcfService.PriceMexService.FoodMonitor GetFoodMonitorById(long AutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/FindFoodMonitors", ReplyAction="http://tempuri.org/IPrice/FindFoodMonitorsResponse")]
        SmartHaiShu.WcfService.PriceMexService.FoodMonitor[] FindFoodMonitors(SmartHaiShu.WcfService.PriceMexService.FoodMonitor findEntity, string filedOrder, System.Nullable<bool> desc, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetFoodMonitorsCounts", ReplyAction="http://tempuri.org/IPrice/GetFoodMonitorsCountsResponse")]
        int GetFoodMonitorsCounts(SmartHaiShu.WcfService.PriceMexService.FoodMonitor findEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/AddFoodMonitor", ReplyAction="http://tempuri.org/IPrice/AddFoodMonitorResponse")]
        long AddFoodMonitor(SmartHaiShu.WcfService.PriceMexService.FoodMonitor fm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/DeleteFoodMonitor", ReplyAction="http://tempuri.org/IPrice/DeleteFoodMonitorResponse")]
        bool DeleteFoodMonitor(long AutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/UpdateFoodMonitor", ReplyAction="http://tempuri.org/IPrice/UpdateFoodMonitorResponse")]
        bool UpdateFoodMonitor(SmartHaiShu.WcfService.PriceMexService.FoodMonitor fm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetDatetimeNewest", ReplyAction="http://tempuri.org/IPrice/GetDatetimeNewestResponse")]
        System.DateTime GetDatetimeNewest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetMonitorSites", ReplyAction="http://tempuri.org/IPrice/GetMonitorSitesResponse")]
        System.Collections.Generic.KeyValuePair<string, string>[] GetMonitorSites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetFoods", ReplyAction="http://tempuri.org/IPrice/GetFoodsResponse")]
        System.Collections.Generic.KeyValuePair<string, string>[] GetFoods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetCategorys", ReplyAction="http://tempuri.org/IPrice/GetCategorysResponse")]
        string[] GetCategorys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetFoodName", ReplyAction="http://tempuri.org/IPrice/GetFoodNameResponse")]
        System.Collections.Generic.KeyValuePair<string, string>[] GetFoodName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrice/GetTableNames", ReplyAction="http://tempuri.org/IPrice/GetTableNamesResponse")]
        string[] GetTableNames();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPriceChannel : SmartHaiShu.WcfService.PriceMexService.IPrice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceClient : System.ServiceModel.ClientBase<SmartHaiShu.WcfService.PriceMexService.IPrice>, SmartHaiShu.WcfService.PriceMexService.IPrice {
        
        public PriceClient() {
        }
        
        public PriceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ExsitesFoodMonitor(long AutoID) {
            return base.Channel.ExsitesFoodMonitor(AutoID);
        }
        
        public SmartHaiShu.WcfService.PriceMexService.FoodMonitor GetFoodMonitorById(long AutoID) {
            return base.Channel.GetFoodMonitorById(AutoID);
        }
        
        public SmartHaiShu.WcfService.PriceMexService.FoodMonitor[] FindFoodMonitors(SmartHaiShu.WcfService.PriceMexService.FoodMonitor findEntity, string filedOrder, System.Nullable<bool> desc, int pageSize, int pageIndex) {
            return base.Channel.FindFoodMonitors(findEntity, filedOrder, desc, pageSize, pageIndex);
        }
        
        public int GetFoodMonitorsCounts(SmartHaiShu.WcfService.PriceMexService.FoodMonitor findEntity) {
            return base.Channel.GetFoodMonitorsCounts(findEntity);
        }
        
        public long AddFoodMonitor(SmartHaiShu.WcfService.PriceMexService.FoodMonitor fm) {
            return base.Channel.AddFoodMonitor(fm);
        }
        
        public bool DeleteFoodMonitor(long AutoID) {
            return base.Channel.DeleteFoodMonitor(AutoID);
        }
        
        public bool UpdateFoodMonitor(SmartHaiShu.WcfService.PriceMexService.FoodMonitor fm) {
            return base.Channel.UpdateFoodMonitor(fm);
        }
        
        public System.DateTime GetDatetimeNewest() {
            return base.Channel.GetDatetimeNewest();
        }
        
        public System.Collections.Generic.KeyValuePair<string, string>[] GetMonitorSites() {
            return base.Channel.GetMonitorSites();
        }
        
        public System.Collections.Generic.KeyValuePair<string, string>[] GetFoods() {
            return base.Channel.GetFoods();
        }
        
        public string[] GetCategorys() {
            return base.Channel.GetCategorys();
        }
        
        public System.Collections.Generic.KeyValuePair<string, string>[] GetFoodName() {
            return base.Channel.GetFoodName();
        }
        
        public string[] GetTableNames() {
            return base.Channel.GetTableNames();
        }
    }
}
