//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaiShu_WebApp.HSSmartDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smarths-ndtv.com", ConfigurationName="HSSmartDataService.ISmartHsService")]
    public interface ISmartHsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/AddMember", ReplyAction="http://smarths-ndtv.com/ISmartHsService/AddMemberResponse")]
        string AddMember(string memberJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/ExistMemberName", ReplyAction="http://smarths-ndtv.com/ISmartHsService/ExistMemberNameResponse")]
        string ExistMemberName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindMember", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindMemberResponse")]
        string FindMember(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindMemberByName", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindMemberByNameResponse")]
        string FindMemberByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/UpdateMember", ReplyAction="http://smarths-ndtv.com/ISmartHsService/UpdateMemberResponse")]
        string UpdateMember(long id, string memberJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/Login", ReplyAction="http://smarths-ndtv.com/ISmartHsService/LoginResponse")]
        string Login(string memberName, string password, string ip, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/UpdateMemberKey", ReplyAction="http://smarths-ndtv.com/ISmartHsService/UpdateMemberKeyResponse")]
        string UpdateMemberKey(string name, string orignalMemberKey, string newMemberKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindAllStreet", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindAllStreetResponse")]
        string FindAllStreet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindCommunityByStreet", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindCommunityByStreetResponse")]
        string FindCommunityByStreet(int street);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindCommunity", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindCommunityResponse")]
        string FindCommunity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindStreetGroup", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindStreetGroupResponse")]
        string FindStreetGroup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/AddSessionVerify", ReplyAction="http://smarths-ndtv.com/ISmartHsService/AddSessionVerifyResponse")]
        string AddSessionVerify(long dateTicks, string key, string confirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/ReadyToUseSessionVerify", ReplyAction="http://smarths-ndtv.com/ISmartHsService/ReadyToUseSessionVerifyResponse")]
        string ReadyToUseSessionVerify(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/CanUseSession", ReplyAction="http://smarths-ndtv.com/ISmartHsService/CanUseSessionResponse")]
        string CanUseSession(long dateTicks, string key, string confirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/CanUseSessionById", ReplyAction="http://smarths-ndtv.com/ISmartHsService/CanUseSessionByIdResponse")]
        string CanUseSessionById(long sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindPostSpanTypeConfig", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindPostSpanTypeConfigResponse")]
        string FindPostSpanTypeConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/FindTypeConfigByCategory", ReplyAction="http://smarths-ndtv.com/ISmartHsService/FindTypeConfigByCategoryResponse")]
        string FindTypeConfigByCategory(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/AddInteractPost", ReplyAction="http://smarths-ndtv.com/ISmartHsService/AddInteractPostResponse")]
        string AddInteractPost(string title, string content, string keyword, string contractInfo, int dataSpan, long memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/GetPostCount", ReplyAction="http://smarths-ndtv.com/ISmartHsService/GetPostCountResponse")]
        string GetPostCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/GetPostTitlesByPage", ReplyAction="http://smarths-ndtv.com/ISmartHsService/GetPostTitlesByPageResponse")]
        string GetPostTitlesByPage(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/GetPostsByPage", ReplyAction="http://smarths-ndtv.com/ISmartHsService/GetPostsByPageResponse")]
        string GetPostsByPage(int pageNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/GetSpecialInteractPost", ReplyAction="http://smarths-ndtv.com/ISmartHsService/GetSpecialInteractPostResponse")]
        string GetSpecialInteractPost(long postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/DeleteInteractPost", ReplyAction="http://smarths-ndtv.com/ISmartHsService/DeleteInteractPostResponse")]
        string DeleteInteractPost(long postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/SocialInsureQuery", ReplyAction="http://smarths-ndtv.com/ISmartHsService/SocialInsureQueryResponse")]
        string SocialInsureQuery(string cardId, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/WeatherInfoToday", ReplyAction="http://smarths-ndtv.com/ISmartHsService/WeatherInfoTodayResponse")]
        string WeatherInfoToday();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/WeatherInfoFuture", ReplyAction="http://smarths-ndtv.com/ISmartHsService/WeatherInfoFutureResponse")]
        string WeatherInfoFuture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smarths-ndtv.com/ISmartHsService/GetTrafficCodeImg", ReplyAction="http://smarths-ndtv.com/ISmartHsService/GetTrafficCodeImgResponse")]
        byte[] GetTrafficCodeImg();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartHsServiceChannel : SmartHaiShu_WebApp.HSSmartDataService.ISmartHsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartHsServiceClient : System.ServiceModel.ClientBase<SmartHaiShu_WebApp.HSSmartDataService.ISmartHsService>, SmartHaiShu_WebApp.HSSmartDataService.ISmartHsService {
        
        public SmartHsServiceClient() {
        }
        
        public SmartHsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartHsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartHsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartHsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddMember(string memberJson) {
            return base.Channel.AddMember(memberJson);
        }
        
        public string ExistMemberName(string name) {
            return base.Channel.ExistMemberName(name);
        }
        
        public string FindMember(long id) {
            return base.Channel.FindMember(id);
        }
        
        public string FindMemberByName(string name) {
            return base.Channel.FindMemberByName(name);
        }
        
        public string UpdateMember(long id, string memberJson) {
            return base.Channel.UpdateMember(id, memberJson);
        }
        
        public string Login(string memberName, string password, string ip, int type) {
            return base.Channel.Login(memberName, password, ip, type);
        }
        
        public string UpdateMemberKey(string name, string orignalMemberKey, string newMemberKey) {
            return base.Channel.UpdateMemberKey(name, orignalMemberKey, newMemberKey);
        }
        
        public string FindAllStreet() {
            return base.Channel.FindAllStreet();
        }
        
        public string FindCommunityByStreet(int street) {
            return base.Channel.FindCommunityByStreet(street);
        }
        
        public string FindCommunity(int id) {
            return base.Channel.FindCommunity(id);
        }
        
        public string FindStreetGroup() {
            return base.Channel.FindStreetGroup();
        }
        
        public string AddSessionVerify(long dateTicks, string key, string confirm) {
            return base.Channel.AddSessionVerify(dateTicks, key, confirm);
        }
        
        public string ReadyToUseSessionVerify(long id) {
            return base.Channel.ReadyToUseSessionVerify(id);
        }
        
        public string CanUseSession(long dateTicks, string key, string confirm) {
            return base.Channel.CanUseSession(dateTicks, key, confirm);
        }
        
        public string CanUseSessionById(long sessionId) {
            return base.Channel.CanUseSessionById(sessionId);
        }
        
        public string FindPostSpanTypeConfig() {
            return base.Channel.FindPostSpanTypeConfig();
        }
        
        public string FindTypeConfigByCategory(int categoryId) {
            return base.Channel.FindTypeConfigByCategory(categoryId);
        }
        
        public string AddInteractPost(string title, string content, string keyword, string contractInfo, int dataSpan, long memberId) {
            return base.Channel.AddInteractPost(title, content, keyword, contractInfo, dataSpan, memberId);
        }
        
        public string GetPostCount() {
            return base.Channel.GetPostCount();
        }
        
        public string GetPostTitlesByPage(int pageNo, int pageSize) {
            return base.Channel.GetPostTitlesByPage(pageNo, pageSize);
        }
        
        public string GetPostsByPage(int pageNo, int pageSize) {
            return base.Channel.GetPostsByPage(pageNo, pageSize);
        }
        
        public string GetSpecialInteractPost(long postId) {
            return base.Channel.GetSpecialInteractPost(postId);
        }
        
        public string DeleteInteractPost(long postId) {
            return base.Channel.DeleteInteractPost(postId);
        }
        
        public string SocialInsureQuery(string cardId, string pwd) {
            return base.Channel.SocialInsureQuery(cardId, pwd);
        }
        
        public string WeatherInfoToday() {
            return base.Channel.WeatherInfoToday();
        }
        
        public string WeatherInfoFuture() {
            return base.Channel.WeatherInfoFuture();
        }
        
        public byte[] GetTrafficCodeImg() {
            return base.Channel.GetTrafficCodeImg();
        }
    }
}
