//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHaiShu.ViewLogic.OpenDataServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpenDataServiceProxy.IOpenDataService")]
    public interface IOpenDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityName", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNameResponse")]
        string GetCommunityName(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenDataService/GetCommunityNotice", ReplyAction="http://tempuri.org/IOpenDataService/GetCommunityNoticeResponse")]
        string GetCommunityNotice(string community);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOpenDataServiceChannel : SmartHaiShu.ViewLogic.OpenDataServiceProxy.IOpenDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenDataServiceClient : System.ServiceModel.ClientBase<SmartHaiShu.ViewLogic.OpenDataServiceProxy.IOpenDataService>, SmartHaiShu.ViewLogic.OpenDataServiceProxy.IOpenDataService {
        
        public OpenDataServiceClient() {
        }
        
        public OpenDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpenDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCommunityName(string address) {
            return base.Channel.GetCommunityName(address);
        }
        
        public string GetCommunityNotice(string community) {
            return base.Channel.GetCommunityNotice(community);
        }
    }
}
